trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- checkout: self
  path: '$(currentDirectory)'
- powershell: |
    pwd
    ls
    Get-Module -ListAvailable | select name
    Install-Module PSScriptAnalyzer -Force | select -expand name
    Get-Module PSScriptAnalyzer -verbose
    write-output "hello"
  displayName: 'Get current directory'

