trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- checkout: self
  path: '$(currentDirectory)'
- powershell: |
    pwd
    Find-Module PSScriptAnalyzer | Install-Module
    Get-Module PSScriptAnalyzer
    write-output "hello"
  displayName: 'Get current directory'

