trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- checkout: self
  path: '$(currentDirectory)'
- powershell: |
    pwd
    Install-PackageProvider -Name NuGet -Force -Scope CurrentUser
    Install-Module -Name PSScriptAnalyzer -Force -Verbose -Scope CurrentUser
    Get-Module PSScriptAnalyzer
  displayName: 'Import Module'
