trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- checkout: self
  path: '$(currentDirectory)'
- powershell: |
    pwd
    Install-PackageProvider -Name NuGet -Force -Scope CurrentUser
    Install-Module -Name PSScriptAnalyzer -Force -Scope CurrentUser
    Invoke-ScriptAnalyzer -Path $(currentDirectory)
  displayName: 'Import Module'
