# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- checkout: self
- powershell: Write-Output Hello, world!
  displayName: 'Run a one-line script'

- powershell: |
    Write-Output Add other tasks to build, test, and deploy your project.
    Write-Output See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
