trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- checkout: self
  path: '$(currentDirectory)'
- powershell: |
    pwd
    ls
    Get-Module -ListAvailable
    Get-Command -Module PSScriptAnalyzer
  displayName: 'Get current directory'

