trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- checkout: self
  path: '$(currentDirectory)'
- powershell: |
    pwd
    ls
    Get-Module -ListAvailable | select name
    Install-Module PSScriptAnalyzer -Force
  displayName: 'Get current directory'

